### ISSUE TITLE
Performance of cost volume layer

### ISSUE THREAD

**Issue by saxenarohan97** [daigo0927/PWC-Net_tf#10]
Hi @daigo0927,

Thanks for your code, I really like your implementation. Good work implementing the warping and cost volume layers - using meshgrid was a particularly clever way of implementing warping.

So I tried running the cost volume layer on full resolution feature maps (with resolution around 300x400). While the layer runs well on small feature map sizes, it takes way too long to run on full resolution images. So my question is, what size of feature maps did you use while training, and how long does it take to run the cost volume layer on that size? Didn't this prove to be a bottleneck while training?

TIA.

**Comment by daigo0927** [comment]
Thanks!

I, and the original paper, input images with the size of (384, 448) while training. In this case, the size of the extracted feature pyramid is (192, 224) -> (96, 112) -> (48, 56) -> (24, 28) -> (12, 14) -> (6, 7). Each of them are fed into cost-volume layer with coarse-to-fine manner.

I'm sorry that I don't know the exact runtime of cost-volume calculation, but in my environment (set search-range of cost volume as 4), it does not seem to be a serious bottleneck.
I think the setting of search-range (note as s) is critical for the runtime of cost volume calculation. This computation increases O(s^2). 

Kindly regards.

**Comment by MrRoboticist** [comment]
In the feature pyramid, isn't the first layer of the pyramid the original input image? That's primarily why I was testing the layer on full resolution images. Although, I think that's not required because the optical flow computation stops at pyramid level 2.

**Comment by saxenarohan97** [comment]
Hi @daigo0927,

I have another question about the cost volume layer. In the PWC-Net paper, they define the correlation operation as:
![image](https://user-images.githubusercontent.com/17175695/45383078-72fe5980-b60a-11e8-858c-bd946366b2cc.png)

That is, they divide the dot product of the 2 feature vectors by the length of the vectors `N`.

However, in your code for the [CostVolumeLayer](https://github.com/daigo0927/PWC-Net_tf/blob/master/modules.py#L157) class, you divide the dot product of the feature vectors by `cost_length` which is `(2*self.s_range+1)**2`. Is there any particular reason for this?

**Comment by daigo0927** [comment]
You're true. I'm going to fix it to divide by N.

**Comment by saxenarohan97** [comment]
It seems that the official implementation of Pwc-Net has divided the dot product by `N*(2*self.s_range+1)**2`. See this: https://github.com/NVlabs/PWC-Net/issues/31.

**Comment by daigo0927** [comment]
Thanks for telling me that.
I don't fully figure out the effect of dividing factor, but I will follow the original implementation :)
