### ISSUE TITLE
Test Script

### ISSUE THREAD

**Issue by bhattaca** [daigo0927/PWC-Net_tf#12]
Hello, When running the test command with the checkpoint you provided. I am getting the following error 

NotFoundError (see above for traceback): Key **pwcdcnet/context/conv2d/bias not found in checkpoint**
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], 

I am using tf 1.8, any idea what I might be doing wrong ? Thanks again for your help.

**Comment by daigo0927** [comment]
Thanks for the kind reporting.

I'm sorry, I have pushed PWCDCNet which is introduced in the original repository, but the trained parameter in this repository is obtained by simple PWCNet model.
Now I train the new model, and am going to make the trained parameter available ASAP.

Kindly regards :)

**Comment by aiguo112** [comment]
Hi @daigo0927 , i am facing this error, my tf version is 1.8.0 , can you please update the testing script if possible. thank you

 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
