### ISSUE TITLE
Regarding the PWCDCNet trained parameter

### ISSUE THREAD

**Issue by RamSrivatsav** [daigo0927/PWC-Net_tf#13]
Hello,
Thanks for your code, it was really helpful. I want to check if the PWCDCNet trained parameters (@ model_600.cpkt files) are of the MPI Sintel dataset. Awaiting your reply.
Thanks,
Ram.

**Comment by daigo0927** [comment]
Thanks for watching.

Yes, model_600.ckpt is obtained by SintelClean, and model_50.ckpt (under model_100epochs_ft_Chairs) is by fine-tuning on FlyingChairs dataset started from model_600.ckpt.

Fine-tuned model seems to well generalized for many kinds input images. I recommend to consider to use it.

kindly regards :)
