### ISSUE TITLE
Adding a LICENSE file to your work

### ISSUE THREAD

**Issue by philferriere** [daigo0927/PWC-Net_tf#14]
Hi @daigo0927 ,

Your work was useful to me when I started implementing PWC-Net using TensorFlow. I want to add links to your work and need to know what kind of license you are sharing your code under.

Would you mind adding a LICENSE file to your repo so that we can reference your work appropriately?

Thank you so much for all your hard work!

PS: If you're interested, my implementation is at https://github.com/philferriere/tfoptflow

**Comment by daigo0927** [comment]
Thanks for your kind suggestion. Your code is also cool.

I'm going to add MIT license in a few days.

**Comment by daigo0927** [comment]
Thanks for the kind suggestion. Your code and notebook are also cool.
I add MIT license.

**Comment by philferriere** [comment]
Thank you for the compliment, @daigo0927 , and for adding a license to your repo.
By the way, If you ever get tired of maintaining your own codebase and/or would like to submit PRs to my repo instead, you are more than welcome to do so! Regards, -- Phil
