### ISSUE TITLE
Training on Custom Dataset 

### ISSUE THREAD

**Issue by NaifahNurya** [daigo0927/PWC-Net_tf#5]
Thank you for this PWC_Net implemented in Tensorflow.
Kindly i would like your help on the following issues;

1.What are the procedure for training custom data set, (Do i need only images without optical flow ground truth or images and its correspondingoptical flow ground truth ).

2.On testing, i get the images of opticaflow which are on the pdf, how can i get only the optical (last optical image and save it for further work).

3The testing consider only two frame, is there a suggestion/means to work on more than one frame extracted from video (arranged in ascending order ) and generate its corresponding opticalflow for all n-1 frames.

**Comment by daigo0927** [comment]
Welcome!

1. training dataset requires paired images **and** ground truth optical flow.
2. using the function vis_flow in flow_utils.py, you can obtain RGB-converted optical flow, then plt.savefig() (which is a function of matplotlib.pyplot) can save the converted optical flow as an image (eg. pdf, png, ...).
3. maybe yes, prepare a list of paired images, and running optical flow estimation (same as test.py) for each pair of the prepared list will satisfy your requirements.
